checks:
  php: true

filter:
  paths:
    - "src/*"

build:
  image: default-bionic

  environment:
    php:
      version: 8.0.11
      ini:
        "xdebug.mode": coverage

  nodes:
    analysis:
      services:
        memcached:
          image: memcached:latest
          ports:
            - 11211

      dependencies:
        override:
          - pecl install memcached

      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      services:
        memcached:
          image: memcached:latest
          ports:
            - 11211

      dependencies:
        override:
          - pecl install memcached
          - composer self-update
          - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      tests:
        override:
          - command: "./vendor/bin/phpunit --coverage-clover ./coverage.xml"
            on_node: 1
            coverage:
              file: coverage.xml
              format: php-clover
